# Generated by Django 4.2.7 on 2025-12-24 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('institute_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MarksBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_marks', models.IntegerField()),
                ('max_marks', models.IntegerField()),
                ('percentile', models.FloatField()),
                ('min_rank', models.IntegerField()),
                ('max_rank', models.IntegerField()),
            ],
            options={
                'ordering': ['-min_marks'],
            },
        ),
        migrations.CreateModel(
            name='Cutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=20)),
                ('quota', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('round_num', models.IntegerField()),
                ('year', models.IntegerField()),
                ('opening_rank', models.IntegerField()),
                ('closing_rank', models.IntegerField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.institute')),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'category', 'quota', 'closing_rank'], name='predictor_c_year_7a49b7_idx')],
            },
        ),
    ]
