# Generated by Django 4.2.7 on 2025-12-24 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('seat_pool', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('open_seats', models.IntegerField(default=0)),
                ('ews_seats', models.IntegerField(default=0)),
                ('obc_seats', models.IntegerField(default=0)),
                ('sc_seats', models.IntegerField(default=0)),
                ('st_seats', models.IntegerField(default=0)),
                ('total_seats', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=2024)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.institute')),
            ],
        ),
        migrations.DeleteModel(
            name='Cutoff',
        ),
        migrations.AddIndex(
            model_name='seatinfo',
            index=models.Index(fields=['year', 'state', 'seat_pool', 'gender'], name='predictor_s_year_e1fe56_idx'),
        ),
        migrations.AddIndex(
            model_name='seatinfo',
            index=models.Index(fields=['year', 'seat_pool'], name='predictor_s_year_9d1625_idx'),
        ),
    ]
