# Generated by Django 4.2.7 on 2025-12-24 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_seatinfo_delete_cutoff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('quota', models.CharField(max_length=20)),
                ('seat_type', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('opening_rank', models.IntegerField()),
                ('closing_rank', models.IntegerField()),
                ('year', models.IntegerField(default=2025)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.institute')),
            ],
        ),
        migrations.DeleteModel(
            name='SeatInfo',
        ),
        migrations.AddIndex(
            model_name='cutoff',
            index=models.Index(fields=['year', 'institute', 'program_name', 'quota', 'seat_type', 'gender'], name='predictor_c_year_39d004_idx'),
        ),
    ]
