# Generated by Django 4.2.7 on 2025-12-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_cutoff_delete_seatinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='institute_type',
            field=models.CharField(blank=True, choices=[('IIT', 'IIT'), ('NIT', 'NIT'), ('IIIT', 'IIIT'), ('GFTI', 'GFTI')], max_length=20),
        ),
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
