# Generated by Django 4.2.7 on 2025-12-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_alter_institute_institute_type_alter_institute_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=50)),
                ('pass_year', models.CharField(choices=[('2026', '2026'), ('2027', '2027'), ('2028', '2028')], max_length=4)),
                ('gender', models.CharField(max_length=50)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('approx_rank', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('otp_code', models.CharField(blank=True, max_length=10)),
                ('otp_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
